remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-minimal

title: Sen Zhang
logo: DSC06033.JPG
description: I am a Ph.D. candidate at Rome Economics Doctorate (RED), Italy. My research interests include Heterogeneous Agents New Keynesian models and empirical macroeconomics.
